### ISSUE TITLE
Missing  ground-truth timestamp annotations file in the rttm format.

### ISSUE THREAD

**Issue by audioprotector** [nii-yamagishilab/PartialSpoof#10]
Hello,
Thanks for the amazing work on Partial Spoof detection. I was going through the code and ran through some issue. 

The code for calculating segment based EER and range based EER requires ref_rttm file "_Path to the ground-truth timestamp annotations file in the rttm format_" and --reco2dur file _Path to the recording duration file_ . These files are not available in the database directory.

The default path for ref_rttm_file is _"../../../database/dev/con_data/rttm_2cls_0sil"_. But there is no such file in the directory.

**Comment by zlin0** [comment]
Hi @BhashaBluff , thanks for your interest! Please download rttms files from [PS_data.tar.gz](https://github.com/nii-yamagishilab/PartialSpoof/files/13612852/PS_data.tar.gz)

I’ll also upload it to a more convenient location soon—sorry for the inconvenience.

**Comment by audioprotector** [comment]
Hi,
Thanks for sharing the annotations file.
