### ISSUE TITLE
Unable to run inference

### ISSUE THREAD

**Issue by cyaaronk** [nii-yamagishilab/PartialSpoof#5]
Dear Author,

I try to follow the steps in PartialSpoof/tree/main/03multireso
under the section "Using Pretrained Models"
when I run :
$bash 00_run.sh 2

I encounter error in multi-reso/01/output/log_output_dev:
size mismatch for m_transform.0.post_nets_utt.layers.4.proj2.weight: copying a param with shape torch.Size([32, 8]) from checkpoint, the shape in current model is torch.Size([8, 2]).
        size mismatch for m_transform.0.post_nets_utt.layers.4.proj2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for m_transform.0.post_nets_utt.fc.weight: copying a param with shape torch.Size([16, 32]) from checkpoint, the shape in current model is torch.Size([4, 8]).

Why it says the dimensions are different?

**Comment by zlin0** [comment]
Sorry, I missed your question earlier. Have you already solved it, or do you still need assistance? Could you provide more information about the issue? Which pre-trained model are you using?

I am guessing you might be using a different SSL model as referenced in [model.py:57](https://github.com/nii-yamagishilab/PartialSpoof/blob/main/03multireso/model.py#L57) and [model.py:180](https://github.com/nii-yamagishilab/PartialSpoof/blob/main/03multireso/model.py#L180) compared to the downloaded one.

**Comment by zlin0** [comment]
I will close it, please reopen it if you still have the same issue.
