### ISSUE TITLE
problem in config in 03multireso

### ISSUE THREAD

**Issue by DanMerry** [nii-yamagishilab/PartialSpoof#8]
Excuse me, I encountered some issues while reproducing the code. Could you please tell me where the config.py for the parameter module-config is located?
![image](https://github.com/nii-yamagishilab/PartialSpoof/assets/52539280/3d133bf2-287f-423e-821c-56d5e4f98cd3)

**Comment by zlin0** [comment]
@DanMerry Hi, thanks for your interest in Partial Spoof. 

Did you follow README carefully? https://github.com/nii-yamagishilab/PartialSpoof/tree/main/03multireso#usuage

The `base` folder is created as the primary directory. you can use it as an example folder for experiments. In all base/00_run.sh scripts, I provided samples for training and inference. You can notice that I assign a value for --module-config config_ps.config_test_on_eval.
I provided two configuration files in the `config_ps` folder. The `--module-config` option will be assigned a configuration file by default.

**Comment by DanMerry** [comment]
Thank you very much for your response. But I have one more question. When loading the pretrained model wav2vec, the task_cfg key was not read from the model.
![image](https://github.com/nii-yamagishilab/PartialSpoof/assets/52539280/f10bcb00-fd6c-4579-9d0a-90e7dcde325d)
# load wav2vec in the s3prl
![image](https://github.com/nii-yamagishilab/PartialSpoof/assets/52539280/bd875d12-0c2e-4f3f-8749-02aaccb28cab)
# the key in the download model from ssl_link="https://dl.fbaipublicfiles.com/fairseq/wav2vec/w2v_large_lv_fsh_swbd_cv.pt"
![image](https://github.com/nii-yamagishilab/PartialSpoof/assets/52539280/482ead1c-4d3a-4793-9a43-6d498f1e865b)
The key of task_cfg is not in the downloaded model. Is the problem existing in the version of the download model or the version of s3prl?

**Comment by Abdullah-Eisa** [comment]
SA @DanMerry ,

I think you are using windows os while trying to run the project. So, you need to change env.sh file to add custom libraries properly.


**If you have some ideas about how to setup the conda environment for the project with specific versions of Python libraries to run the PartialSpoof project properly , it will be great if you share them with me.**


This new env.sh file suitable for windows might help you:

```
#!/bin/bash
# Load conda environment if necessary
# ROOT_PATH=`pwd`
ROOT_PATH=$(pwd -W) # Use `pwd -W` to get the correct Windows path
XW_PATH="${ROOT_PATH}/project-NN-Pytorch-scripts.202102"
MODULES_PATH="${ROOT_PATH}/modules"
S3PRL_PATH="${MODULES_PATH}/s3prl"

export PS_PATH="$ROOT_PATH"
echo "PS_PATH= $PS_PATH"
# export PYTHONPATH="${XW_PATH}:${ROOT_PATH}:${PYTHONPATH}:${MODULES_PATH}:${S3PRL_PATH}"
export PYTHONPATH="${XW_PATH};${ROOT_PATH};${PYTHONPATH};${MODULES_PATH};${S3PRL_PATH}"
echo "PYTHONPATH= $PYTHONPATH"


```

**Comment by zlin0** [comment]
@DanMerry Hi, thank you for providing detailed information for your question. I reimplement this error using the lastest version of s3prl. 
This error can be solved if you download the model using links in `s3prl/s3prl/upstream/*/hubconf.py`. Those links starts with "https://huggingface.co/s3prl/converted_ckpts/..." provided checkpoint converted by s3prl, which includes the new introduced attribute "task_cfg" 

You will get this error when you use the pretrained model downloaded from huggingface/fairseq.

**Comment by DanMerry** [comment]
Thanks very much. You previously provided a link to download the w2v2 model. Now it can be trained, but during inference, according to the readme.md file, there are the following problems:
![image](https://github.com/user-attachments/assets/cb7e35f8-2d6e-4acd-965c-8b6269f9e771)

**Comment by DanMerry** [comment]
It seems like the 954 is the size of the score_ali and target_ali, 7642 is the batchsize*954. Different size cannot be concated, how to solve it.
![image](https://github.com/user-attachments/assets/6ac12126-af6a-4375-9c2c-d20411d7159d)
